---
title: "長庚大學 大數據分析方法 作業三"
output: github_document
---



    

## 網站資料爬取
```{r}
library(rvest)
PTTNBA<-"https://www.ptt.cc/bbs/NBA/index.html"
for(n in 1:6){
  pttContent<-read_html(PTTNBA)
  pageup <- pttContent %>% html_nodes(".btn-group a") %>% html_attr("href")
  post_title <- pttContent %>% html_nodes(".title") %>% html_text()
  post_push <- pttContent %>% html_nodes(".nrec") %>% html_text()
  post_author <- pttContent %>% html_nodes(".author") %>% html_text()
  PttNBA_posts <- data.frame(Title = post_title,
                               PushNum = post_push,
                               Author = post_author)
  PTTNBA <- paste("https://www.ptt.cc",pageup[4], sep="")
  nam <- paste("PttNBA_posts",n,sep="")
  assign(nam, PttNBA_posts)
}

PttNBA_posts_All <- rbind(PttNBA_posts1,PttNBA_posts2,PttNBA_posts3,PttNBA_posts4,PttNBA_posts5,PttNBA_posts6)
```

## 爬蟲結果呈現
```{r}
knitr::kable(
  PttNBA_posts_All[c("Title", "PushNum", "Author")]
)

```

## 解釋爬蟲結果 
```{r}
str(PttNBA_posts_All)
table(PttNBA_posts_All$Author)


```
總共117篇文章
名字為Rombo的總共發了18篇是最多文章的作者

```{r}
table(PttNBA_posts_All$Title)
```
按照標題看起來，目前大多數的文章討論比賽的比數或狀況 
最常被討論的球星是詹姆士